### ISSUE TITLE
Mob Killing Event Issue

### ISSUE THREAD

**Issue by Rhbarber** [ManelNavola/MCInteractive#2]
Paper 334 1.15.2

Multiple Events Issue when mob killing. Also some of the mobs are being "invalid" and randomly being valid again, for example Guardians, Enderdragon or Wither, bits granting for this mobs are random, sometimes they give bits and sometimes they become "Unvalid mobs"

https://pastebin.com/3V5SEdCR

**Comment by ManelNavola** [comment]
First of all, thanks for posting the issue!

Bits are given randomly when killing a hostile mob, and a system has been implemented to prevent farming, for this reason, bosses such as elder guardians, enderdragons and withers have a noticeable delay between being valid and unvalid for obtaining bits.

In the next version I am planning to expand upon the configuration of the plugin, so those parameters will be also able to be changed.

As for the error event that is being printed, I haven't found it while testing locally, are you by any change using plugins that involve combat in any way?

Thanks again for posting the issue and sorry for the issue!

**Comment by Rhbarber** [comment]
Oh yeah, didnt think about that, im using CombatLogX and OldCombatMechanics, so it may be not your fault haha

And thanks for clarifying the bits mechanics!

**Comment by ManelNavola** [comment]
No problem! And I think the error that is logging is due to an entity being killed by other means than direct player damage. That should mean it has no impact on the plugin's mechanics, but anyways I will fix it in the next release!
