### ISSUE TITLE
Mojibake issue

### ISSUE THREAD

**Issue by H2Owater425** [ManelNavola/MCInteractive#3]
First of all, thanks to make this plugin.
I kept finding a plugin like this, and this is very fit for me!

Unfortunately, I'm Korean so I usually don't use English much.
When I use this plugin and Twitch's Korean chatting appears in Minecraft, then mojibake happens like in the picture.

![mojibake picture](https://user-images.githubusercontent.com/50160366/84754763-cb426680-affb-11ea-8ddc-a68969a5f026.png)
_(English chattings are working great)_

Could you fix this?

**Comment by ManelNavola** [comment]
Hello! First of all thanks for reporting the issue :)
I have just uploaded a new version to Spigot and CraftBukkit that adds UTF-8 support, which should fix the issue.
Try it out and tell me if it works!

**Comment by H2Owater425** [comment]
I tried out for new release of the plugin and it worked very well, thank you!

![주석 2020-06-18 213918](https://user-images.githubusercontent.com/50160366/85021318-ac370680-b1ac-11ea-8262-5d2ac043cb6c.png)
_(From simple words to complex words, I tested them in Korean.)_
