### ISSUE TITLE
Several Events Issues

### ISSUE THREAD

**Issue by Rhbarber** [ManelNavola/MCInteractive#5]
https://pastebin.com/Gg0Sdrrv

Paper-372 1.15.2

**Comment by ManelNavola** [comment]
Hello! The error event it's giving should not affect the plugin's mechanics at all, still that will be fixed in the next update :)

**Comment by ManelNavola** [comment]
Hey! First of all, thanks for reporting the issue.

This log makes me think the bot could not connect to Twitch IRC successfully. Has another error log printed before that by any chance, along the lines of "Could not start bot! Restart the plugin and if the issue persists contact the developer"?

It may also be that the player joined before the Twitch IRC bot was created (ddin't know this could happen). Did the player join right when the server opened? Do you have any plugins that influence or modify the mechanics of player joining in any way?

Thanks for your time,
~ Manel
